### ISSUE TITLE
Change ElementTypes to Enum 

### ISSUE THREAD

**Issue by sandstone991** [The-Zagy/zagydraw#11]
**Is your feature request related to a problem? Please describe.**
I think it'd be better computationally-wise to change to the current type of ElementTypes to an Enum

**Comment by vaishnavhiren1993** [comment]
Helllo @sandstone991 
I'll give it a shot

**Comment by vaishnavhiren1993** [comment]
Why it should enum?

**Comment by vaishnavhiren1993** [comment]
Can you pls elaborate?

**Comment by sandstone991** [comment]
@vaishnavhiren1993  Thanks for giving our app a shot, by far you're a first contributer or (to-be contributer), anyways currently the type ElementTypes is a string literal type 
```ts
type ElementTypes = "rectangle" | "line" | "text" | "handdrawn";
```
Now this isn't a problem of itself, the problem is the while rendering we have to check the type on every frame to redirect the renderer to the correct elementRenderer function.
I thought it'd be a minor optimization if we didn't have to do this and used an enum instead, so instead of comparing two string together the renderer only have to check on a number.
I hope this clarified everything still don't hesitate to ask any question!

**Comment by vaishnavhiren1993** [comment]
One possible solution without breaking changes is to use
`const enum ElementTypesEnum {
    none = 0,
    rectangle,
    line,
    text,
    handdrawn
}
type ElementTypes = keyof typeof ElementTypesEnum;`


![image](https://github.com/The-Zagy/zagydraw/assets/11805630/2d656024-d008-424a-b1fe-968f0acc0cdd)

Your call pls on this

Ref: https://dev.to/ylerjen/use-typescript-const-assertion-instead-of-enums-mfn

**Comment by nagy-nabil** [comment]
hey @vaishnavhiren1993 , how are you today?
i hear you TS enums are not that great and it's always advised against.

**so I guess we would go with object as const option**, because const enum needs specific tsconfig and we're planning to publish the app as a component and wouldn't be good DX to push certain tsconfig flags to use our component, for more context [const-enum-pitfalls](https://www.typescriptlang.org/docs/handbook/enums.html#const-enum-pitfalls), and at this point, we still don't mind breaking changes.
I hope this clarifies everything still don't hesitate to ask any questions!

**Comment by vaishnavhiren1993** [comment]
Update you soon.
@sandstone991

**Comment by sandstone991** [comment]
I'm gonna close this issue, I'm happy with the current implementation and since we have to pass the shape as a string to `rough.generator` anyways, using enums would cause unnecessary complication.
